namespace CSharpRisohEditor.Core;

/// <summary>
/// Represents a Win32 resource file (EXE, DLL, RC, RES)
/// Main resource management class similar to RisohEditor's main functionality
/// </summary>
public class ResourceFile
{
    /// <summary>
    /// File path
    /// </summary>
    public string FilePath { get; set; } = string.Empty;

    /// <summary>
    /// All resources in the file
    /// </summary>
    public List<ResourceEntry> Resources { get; set; } = new();

    /// <summary>
    /// Load resources from a file
    /// </summary>
    public bool Load(string filePath)
    {
        FilePath = filePath;
        Resources.Clear();

        var extension = Path.GetExtension(filePath).ToLowerInvariant();
        
        return extension switch
        {
            ".exe" or ".dll" => LoadFromPE(filePath),
            ".rc" => LoadFromRC(filePath),
            ".res" => LoadFromRES(filePath),
            _ => false
        };
    }

    /// <summary>
    /// Save resources to a file
    /// </summary>
    public bool Save(string filePath)
    {
        var extension = Path.GetExtension(filePath).ToLowerInvariant();
        
        return extension switch
        {
            ".rc" => SaveToRC(filePath),
            ".res" => SaveToRES(filePath),
            _ => false
        };
    }

    /// <summary>
    /// Load from PE (EXE/DLL) file
    /// </summary>
    private bool LoadFromPE(string filePath)
    {
        // TODO: Implement PE resource loading
        // This would use Win32 API or a library like dnlib or AsmResolver
        return false;
    }

    /// <summary>
    /// Load from RC (Resource Script) file
    /// </summary>
    private bool LoadFromRC(string filePath)
    {
        // TODO: Implement RC parsing
        return false;
    }

    /// <summary>
    /// Load from RES (Compiled Resource) file
    /// </summary>
    private bool LoadFromRES(string filePath)
    {
        // TODO: Implement RES loading
        return false;
    }

    /// <summary>
    /// Save to RC (Resource Script) file
    /// </summary>
    private bool SaveToRC(string filePath)
    {
        try
        {
            using var writer = new StreamWriter(filePath);
            writer.WriteLine("// Generated by CSharpRisohEditor");
            writer.WriteLine();

            foreach (var resource in Resources)
            {
                writer.WriteLine(resource.ToRC());
                writer.WriteLine();
            }

            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Save to RES (Compiled Resource) file
    /// </summary>
    private bool SaveToRES(string filePath)
    {
        // TODO: Implement RES generation
        return false;
    }

    /// <summary>
    /// Add a resource
    /// </summary>
    public void AddResource(ResourceEntry resource)
    {
        Resources.Add(resource);
    }

    /// <summary>
    /// Remove a resource
    /// </summary>
    public bool RemoveResource(ResourceEntry resource)
    {
        return Resources.Remove(resource);
    }

    /// <summary>
    /// Find resources by type
    /// </summary>
    public List<ResourceEntry> FindResourcesByType(ResourceType type)
    {
        return Resources.Where(r => r.Type == type).ToList();
    }
}
